server:
  port: 8076
spring:
  application:
    name: zookeeper-server
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181
      discovery:
        register: false
        instance-host: localhost
        instance-port: ${server.port}
